cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('cart', views.cart_view, name='cart-view'),
    path('clear-cart/', views.clear_cart, name='clear-cart'),
    path('delete/<id>/', views.delete_item, name='delete-item'),
    path('check-out', views.cart_check_out, name='cart-check-out'),
    path('update-item/', views.update_cart_Item, name='update-cart-Item'),
    path('order-porcess/', views.order_process, name='order-process'),
    path('pdf-invoice/<id>', views.render_pdf_invoice, name='render-pdf-invoice'),

]

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views



app_name = "products"
urlpatterns = [
    path('', views.products_home, name='products-home')
]

shoppingcart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('products.urls')),
                  path('cart/', include('cart.urls')),
                  path('utilities/', include('utilities.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utilities/urls.py
from django.contrib import admin
from django.urls import path
from . import views



app_name = "utilities"
urlpatterns = [
     path("signup/", views.signup, name="sign-up"),
     path("login_user", views.login_user, name="login_user"),
      path("logout_user", views.logout_user, name="logout_user"),

]

products/models.py
from django.db import models

from utilities.models import PriceUnit, ItemUnit


# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Category Type')
    description = models.TextField(max_length=500, blank=True, null=True, verbose_name='Category Description')

    class Meta:
        verbose_name_plural = 'Category List'

    def __str__(self):
        return self.name


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='Product Name')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='product_category',
                                 verbose_name='Product Category')
    product_price = models.FloatField(verbose_name='unit price')
    price_currency = models.ForeignKey(PriceUnit, on_delete=models.CASCADE, verbose_name='Currency')
    unit = models.ForeignKey(ItemUnit, on_delete=models.CASCADE, verbose_name='Unit')
    available_qty = models.FloatField(default=0, verbose_name='Available Quantity')
    description = models.TextField(max_length=500, blank=True, null=True, verbose_name='Product Description')
    product_image = models.ImageField(upload_to='products/images', blank=True, null=True, verbose_name='Product Image')

    def __str__(self):
        return self.product_name

products/views.py
from django.shortcuts import render

from cart.models import Cart
from utilities.models import Customer
from .models import Product
# Create your views here.
def products_home(request):
    items = Product.objects.all()
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user,)
        # using get_or_create:
        cart , created = Cart.objects.get_or_create(customer=customer, finished=False)
        # Getting cart items attached to that cart
        cart_items = cart.cartitems_set.all()
        numbers_of_items = cart.number_of_purchased_items
    else:
        cart_items = []
        cart={}
        numbers_of_items = 0


    context={
        'items':items,
        'cart_items':cart_items,
        'numbers_of_items':numbers_of_items,
    }
    return render(request, 'products.html', context)

products/templates/base.html
{% load static %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="robots" content="all,follow">
 <link rel="shortcut icon" href="/static/images/straweberry.png">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
<link rel="stylesheet" href="/static/css/style.sea.css" id="theme-stylesheet">

 <script type="text/javascript">
    var user = "{{ request.user }}"
    function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getToken('csrftoken')

    function getCookie(name) {
        // Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";");
        // Loop through the array elements
        for(var i = 0; i < cookieArr.length; i++) {
            var cookiePair = cookieArr[i].split("=");

            /* Removing whitespace at the beginning of the cookie name
            and compare it with the given string */
            if(name == cookiePair[0].trim()) {
                // Decode the cookie value and return
                return decodeURIComponent(cookiePair[1]);
            }
        }

        // Return null if not found
        return null;
    }
    var cart = JSON.parse(getCookie('cart'))

    if (cart == undefined){
        cart = {}
        console.log('Cart Created!', cart)
        document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
    }

    </script>

{% block title %}


{% endblock %}
</head>


  <body>
    <div class="page">
      <!-- Main Navbar-->
   <header class="header z-index-50">
        <nav class="navbar py-3 px-0 shadow-sm text-white position-relative">

          <div class="container-fluid w-100">
            <div class="navbar-holder d-flex align-items-center justify-content-between w-100">
              <!-- Navbar Header-->
              <div class="navbar-header">
                <!-- Navbar Brand -->
                  <a class="navbar-brand d-none d-sm-inline-block" href="{% url 'products:products-home' %} ">
                    <div class="brand-text d-none d-lg-inline-block"><strong>Dashboard</strong></div>
                  </a>
              </div>
              <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">


              {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'cart:cart-view' %}">
                   <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart4" viewBox="0 0 20 20">
                  <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>
                </svg><span class="badge bg-orange badge-corner fw-normal">
                 {{ numbers_of_items }}
                  </span>
                    </a>
                </li>
              {% else %}
                 <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'utilities:login_user' %}">
                   <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-cart4" viewBox="0 0 20 20">
                  <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>
                </svg><span class="badge bg-orange badge-corner fw-normal">
                 {{ numbers_of_items }}
                  </span>
                    </a>
                </li>
              {% endif %}
             {% if request.user.is_authenticated %}
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'utilities:logout_user' %}"> <span class="d-none d-sm-inline">Log out</span>
                    <svg class="svg-icon svg-icon-xs svg-icon-heavy">
                    </svg></a></li>


                 <li class="nav-item"><a class="nav-link text-white" href="{% url 'admin:products_product_changelist' %}"> <span class="d-none d-sm-inline">Admin</span>
                    <svg class="svg-icon svg-icon-xs svg-icon-heavy">
                    </svg></a></li>
                  {% else %}
                       <li class="nav-item"><a class="nav-link text-white" href="{% url 'utilities:login_user' %}"> <span class="d-none d-sm-inline">Log in</span>
                    <svg class="svg-icon svg-icon-xs svg-icon-heavy">
                    </svg></a></li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </header>


      <div class="page-content d-flex align-items-stretch">
        <div class="content-inner w-100">


            {% block content %}



            {% endblock %}

          <footer class="position-absolute bottom-0 bg-darkBlue text-white text-center py-3 w-100 text-xs" id="footer">
            <div class="container-fluid">
              <div class="row gy-2">
                <div class="col-sm-6 text-sm-start">
                  <p class="mb-0"></p>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </div>
    </div>

products/templates/products.html
{% extends 'base.html' %}
       {% block title %}

<title>Market Products </title>
        {% endblock %}
{% block content %}
<section class="pb-0">
<div class="container-fluid">
    <h3 class="mb-0 p-1 text-hover-success" align="center">Grocery market products  </h3>
  <div class="card mb-0">
    <div class="card-body">
      <div class="row gx-5 bg-white">
      {% if messages %}
            {% for message in messages %}
              {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
              <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Item Added!</strong> {{ request.user.first_name }}, {{ message }}
              </div>
              {% endif %}

              {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
              <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Info!</strong> {{ message }}
              </div>
              {% endif %}

              {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
              <div class="alert alert-warning alert-dismissable">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                <strong>Sorry!</strong> {{ message }}
              </div>
              {% endif %}

              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
              <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Error!</strong> {{ message }}
              </div>
              {% endif %}

            {% endfor %}
          {% endif %}
             <!-- Item -->
            <div class="card-group">
                {% for item in items %}
                     <div class="col-xl-3 col-sm-6 py-4 ">
                          <div class="d-flex align-items-center">
                            <div class="card">
                               {% if item.product_image %}<img src="{{ item.product_image.url }}" class="card-img-top" width="250" height="250" alt="...">{% else %}<img src="/static/images/cart.jpg" class="card-img-top" alt="...">{% endif %}
                                <div class="card-body">
                                    <h5 class="card-title" style="float:left;">{{ item.product_name }}</h5>
                                    <h5 class="card-title" style="float:right;">{{ item.category.name }}</h5>
                                </div>


                            {% if item.available_qty > 0  %}
                               <div class="card-body">
                                     available in store<a class="badge rounded-pill bg-info ms-2 text-xs">  {{ item.available_qty }} {{ item.unit }}</a>
                                </div>
                                <div class="card-body">
                                  <p class="card-text">{{ item.description|safe }}</p>
                                </div>
                                <div class="card-footer">
                                    {% if request.user.is_authenticated %}
                                     <button class="update-cart btn btn-success"  data-item="{{ item.id }}"  data-action="add">Add to Cart</button>
                                    <h3 style="float:right;">{{ item.product_price }} {{ item.price_currency }}</h3>
                                    {% else %}
                                     <a class="update-cart btn btn-info" href="{% url 'utilities:login_user' %}">Buy This Item</a>
                                    {% endif %}
                                </div>
                                   {% else %}

                                <div class="card-body">
                                    Not Available now<a class="badge rounded-pill bg-danger ms-2 text-xs">  </a>
                                </div>
                                <div class="card-body">
                                  <p class="card-text">{{ item.description|safe }}</p>
                                </div>
                                 <div class="card-footer">
                                    {% if request.user.is_authenticated %}
                                    <a class="btn btn-outline-danger">out of stock </a>
                                    {% else %}
                                     <a class="btn btn-outline-danger">out of stock </a>
                                    {% endif %}
                                </div>
                            {% endif %}
                              </div>

                          </div>
                    </div>
                  {% endfor %}
            </div>

      </div>
    </div>
  </div>
</div>
</section>
    <script>

       const updateBttn = document.getElementsByClassName("update-cart");
        for (let i = 0; i < updateBttn.length; i++) {
            updateBttn[i].addEventListener("click", function(){
                var itemId = this.dataset.item;
                var action = this.dataset.action;
                updateOrder(itemId, action)

                    })
                }

            function updateOrder(itemId , action){
                console.log('User is Logged, Sending Data')
                var url =  '/cart/update-item/'
                fetch(url,{
                    method:'POST',
                    headers:{
                       'Content-Type':'application/json',
                        'X-CSRFToken':csrftoken,
                    },
                    body:JSON.stringify({'itemId':itemId, 'action': action})

                })
                    .then((response) => {
                       return response.json();
                    })
                    .then((data) => {
                        location.reload()
                    });
            }



    </script>



{% endblock %}