cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "cart"
urlpatterns = [
    path('cart', views.cart_view, name='cart-view'),
    path('clear-cart/', views.clear_cart, name='clear-cart'),
    path('delete/<id>/', views.delete_item, name='delete-item'),
    path('check-out', views.cart_check_out, name='cart-check-out'),
    path('update-item/', views.update_cart_Item, name='update-cart-Item'),
    path('order-porcess/', views.order_process, name='order-process'),
    path('pdf-invoice/<id>', views.render_pdf_invoice, name='render-pdf-invoice'),

]

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views



app_name = "products"
urlpatterns = [
    path('', views.products_home, name='products-home')
]

shoppingcart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('products.urls')),
                  path('cart/', include('cart.urls')),
                  path('utilities/', include('utilities.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
import datetime

from django.db import models
from utilities.models import Customer
from products.models import Product


# Create your models here.
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT, null=True, blank=True)
    finished = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    payment_date = models.CharField(max_length=100, blank=True, null=True)

    def total_cart_price(self):
        return CartItems.cart_get_total(self.cartitems_set)

    def number_of_purchased_items(self):
        return CartItems.cart_get_number_of_items(self.cartitems_set)

    def get_paymenet_date(self):
        try:
            payment_date = datetime.datetime.fromtimestamp(float(self.payment_date))
            return str(payment_date)
        except:
            payment_date = 'Not paid yet!'
            return payment_date

    def __str__(self):
        return 'Cart ' + str(self.id)


# the model that send the signal to PRODUCT Model to update stock quantity
class CartItems(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=0)
    total_price = models.IntegerField(default=0)

    @property
    def get_total(self):
        return self.quantity * self.product.product_price

    @staticmethod
    def cart_get_total(items):
        cart_total_price = items.aggregate(models.Sum('total_price'))['total_price__sum']
        return cart_total_price if cart_total_price else 0

    @staticmethod
    def cart_get_number_of_items(items):
        number_of_purchased_items = items.aggregate(models.Sum('quantity'))['quantity__sum']
        return number_of_purchased_items if number_of_purchased_items else 0

    def save(self, **kwargs):
        self.total_price = self.quantity * self.product.product_price
        super(CartItems, self).save(**kwargs)

cart/views.py
import datetime
from django.shortcuts import render, redirect
from django.template.loader import get_template
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
import json
from .models import *
from xhtml2pdf import pisa


# Create your views here.
def cart_view(request):
    customer = request.user.customer
    # using get_or_create:
    cart, created = Cart.objects.get_or_create(customer=customer, finished=False)
    # Getting cart items attached to that cart
    cart_items = cart.cartitems_set.all()
    numbers_of_items = cart.number_of_purchased_items

    context = {
        'cart_items': cart_items,
        'numbers_of_items': numbers_of_items,
        'cart': cart,
    }
    return render(request, 'cart.html', context)


def update_cart_Item(request):
    data = json.loads(request.body)
    itemId = data['itemId']
    action = data['action']
    print('Action:', action)
    print('Item:', itemId)
    customer = request.user.customer
    item = Product.objects.get(id=itemId)
    cart, created = Cart.objects.get_or_create(customer=customer, finished=False)
    cartitem, created = CartItems.objects.get_or_create(cart=cart, product=item)

    if action == 'add':
        if cartitem.product.available_qty > cartitem.quantity:
            cartitem.quantity = (cartitem.quantity + 1)
            messages.success(request, 'your cart now contains ' + str(cartitem.quantity) + ' ' + str(
                cartitem.product.unit) + ' of ' + str(cartitem.product.product_name))
        else:
            messages.warning(request, 'There is only ' + str(cartitem.product.available_qty) + ' ' + str(
                cartitem.product.unit) + ' of ' + str(cartitem.product.product_name) + ' left in stock')
    elif action == 'remove':
        cartitem.quantity = (cartitem.quantity - 1)
        messages.info(request, 'your cart now contains ' + str(cartitem.quantity) + ' ' + str(
            cartitem.product.unit) + ' of ' + str(cartitem.product.product_name))
    cartitem.save()

    if cartitem.quantity <= 0:
        messages.error(request, 'The ' + str(
            cartitem.product.product_name) + ' will be deleted form your cart, if you wish to order this item again, please press continue shopping')
        cartitem.delete()
    return JsonResponse('Item Added to the cart', safe=False)


def clear_cart(request):
    customer = request.user.customer
    cart, created = Cart.objects.get_or_create(customer=customer, finished=False)
    cart_items = cart.cartitems_set.all()
    cart_items.delete()
    return redirect('cart:cart-view')


def delete_item(request, id):
    cart_item = CartItems.objects.get(id=id)
    cart_item.delete()
    return redirect('cart:cart-view')


def cart_check_out(request):
    customer = request.user.customer
    cart, created = Cart.objects.get_or_create(customer=customer, finished=False)
    cart_items = cart.cartitems_set.all()
    numbers_of_items = cart.number_of_purchased_items

    context = {
        'cart_items': cart_items,
        'numbers_of_items': numbers_of_items,
        'cart': cart,
    }
    return render(request, 'check-out.html', context)


def order_process(request):
    payment_date = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    customer = request.user.customer
    cart, created = Cart.objects.get_or_create(customer=customer, finished=False)
    cart.payment_date = payment_date
    cart.finished = True
    cart.save()
    return JsonResponse('Order Completed.. thank you', safe=False)


def render_pdf_invoice(request, id):
    template_src = 'pdf-invoice.html'
    customer = request.user.customer
    cart = Cart.objects.get(id=id)
    cart_items = cart.cartitems_set.all()
    payment_date = datetime.datetime.now()

    context = {
        'customer':customer,
        'cart_items': cart_items,
        'payment_date': payment_date,
        'cart': cart,
    }
    pdf_name = str(customer.user.first_name) + ' ' + str(customer.user.last_name) + ' # invoice -' + str(cart.id)+'.pdf'
    template = get_template(template_src)
    html = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{pdf_name}"'
    pdf = pisa.CreatePDF(html, dest=response)
    if pdf.err:
        return messages.error(request, 'Cannot Download Your invoice right now ')

    return response

cart/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
   {% block title %}

<title>{{ request.user.first_name }} {{ request.user.first_name }} Cart</title>
        {% endblock %}


     <div class="container">
  <section class="pb-0">
      <div class="container-fluid">
            <div class="row gy-4">
               <div class="card mb-0">
                    <div class="card-body">
                      <div class="row gx-5 bg-white">
                        {% if messages %}
                        {% for message in messages %}
                          {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                          <div class="alert alert-success alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Item Added!</strong> {{ request.user.first_name }}, {{ message }}
                          </div>
                          {% endif %}
                          {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                          <div class="alert alert-info alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Info!</strong> {{ request.user.first_name }}, {{ message }}
                          </div>
                          {% endif %}

                          {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                          <div class="alert alert-warning alert-dismissable">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Sorry!</strong> {{ request.user.first_name }},  {{ message }}
                          </div>
                          {% endif %}

                          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                          <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>{{ request.user.first_name }}!</strong> {{ message }}
                          </div>
                          {% endif %}
                        {% endfor %}
                      {% endif %}
                       <div class="table">
                            <table class="table mb-0 table-bordered">
                                <tr>
                                    <th><h5>Items: <strong>{{cart.number_of_purchased_items}}</strong></h5></th>
                                    <th><h5>Total:<strong> {{cart.total_cart_price|floatformat:2}}</strong></h5></th>
                                    {% if cart_items.count > 0 %}
                                    <th><a class="btn btn-success" href="{% url 'cart:cart-check-out' %}">Checkout</a></th>
                                    {% else %}
                                   <th><a class="btn btn-info">No items for checking out</a></th>
                                    {% endif %}
                                    <th><a class="btn btn-dark" href="{% url 'products:products-home' %}">Continue Shopping</a></th>
                                    <th><a class="btn btn-danger" href="{% url 'cart:clear-cart' %}">Clear Cart items</a></th>
                                </tr>
                            </table>
                            <br>
                            <table  class="table mb-0 table-bordered">
                              <thead>
                                    <tr>
                                        <th>product</th>
                                        <th>Unit Price</th>
                                        <th>Quantity</th>
                                        <th>Total</th>
                                        <th>Remove</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for item  in cart_items %}
                                <tr>
                                    <td ><p>{{item.product.product_name}}</p></td>
                                    <td><p>{{item.product.product_price}}</p></td>
                                    <td>

                                        <div style="display: inline-block">
                                             <a class="badge rounded-pill bg-info ms-2 text-xs"> <img data-item="{{item.product.id}}"  data-action="add" width="15px" class="update-cart" src="{% static  'images/plus.jpg' %}"></a>
                                            <a class="badge rounded-pill bg-info ms-2 text-xs">{{item.quantity}}</a>
                                             <a class="badge rounded-pill bg-info ms-2 text-xs"> <img data-item="{{item.product.id}}" data-action="remove"  width="15px" class=" update-cart" src="{% static  'images/minus.jpg' %}"></a>
                                        </div>
                                    </td>
                                    <td>{{item.total_price|floatformat:2}}</td>
                                 <th><a class="btn btn-danger" href="{% url 'cart:delete-item' item.id  %}">Remove</a></th>
                                </tr>
                                {% endfor %}
                            </tbody>
                            </table>
                        </div>
                    </div>
                     </div>
                    </div>
                 </div>
              </div>
         </section>
     </div>
 <script>

       const updateBttn = document.getElementsByClassName("update-cart");
        for (let i = 0; i < updateBttn.length; i++) {
            updateBttn[i].addEventListener("click", function(){
                var itemId = this.dataset.item;
                var action = this.dataset.action;
                console.log('itemId:', itemId, 'Action:', action)
                console.log('User:', user)
                if (user == 'AnonymousUser'){
                addCookieItem(itemId, action)
             }else{
                updateOrder(itemId, action)
		}
            })
        }

        function updateOrder(itemId , action){
            console.log('User is Logged, Sending Data')
            var url =  '/cart/update-item/'

            fetch(url,{
                method:'POST',
                headers:{
				   'Content-Type':'application/json',
                    'X-CSRFToken':csrftoken,
                },
                body:JSON.stringify({'itemId':itemId, 'action': action})

            })
                .then((response) => {
                   return response.json();
                })
                .then((data) => {
                    location.reload()
                });
           }

            function addCookieItem(productId, action){
                console.log('User is not authenticated')

                if (action === 'add'){
                    if (cart[productId] === undefined){
                    cart[productId] = {'quantity':1}

                    }else{
                        cart[productId]['quantity'] += 1
                    }
                }

                if (action === 'remove'){
                    cart[productId]['quantity'] -= 1

                    if (cart[productId]['quantity'] <= 0){
                        alert('The Item will be deleted..!')
                        delete cart[productId];
                    }
                }
                console.log('CART:', cart)
                document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"

                location.reload()
            }
    </script>


{% endblock content %}

cart/templates/check-out.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
<title>Check out - # {{ cart.id }}</title>
{% endblock %}
{% block content %}
 <div class="container">
{% if messages %}
                        {% for message in messages %}
                          {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                          <div class="alert alert-success alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Item Added!</strong> {{ request.user.first_name }}, {{ message }}
                          </div>
                          {% endif %}
                          {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                          <div class="alert alert-info alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>Info!</strong> {{ request.user.first_name }}, {{ message }}
                          </div>
                          {% endif %}

                          {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                          <div class="alert alert-warning alert-dismissable">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Sorry!</strong> {{ request.user.first_name }},  {{ message }}
                          </div>
                          {% endif %}

                          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                          <div class="alert alert-danger alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <strong>{{ request.user.first_name }}!</strong> {{ message }}
                          </div>
                          {% endif %}
                        {% endfor %}
                      {% endif %}
  <section class="pb-0">
       <div class="container-fluid">
              <div class="row gy-4">

                 <div class="card mb-0">
                            <div class="card-body">
                              <div class="row gx-5 bg-white">
                                <!-- Item -->
                                    <br/>
                                   <div class="table" >
                    <table  class="table mb-0 table-bordered">
                    <thead>
                        <tr>
                            <th>product</th>
                            <th>Unit Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                        </tr>
                        </thead>
                    <tbody>
                        {% for item  in cart_items %}
                    <tr>
                            <td>{{item.product.product_name}}</td>
                            <td>{{item.product.product_price}} {{item.product.price_currency }}</td>
                            <td>{{item.quantity}}  {{item.product.unit }} </td>
                            <td>{{item.get_total|floatformat:2}} {{item.product.price_currency }}</td>

                    </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
					<tr>
						<th><h5>Items: <strong>{{cart.number_of_purchased_items}}</strong></h5></th>
						<th><h5>Total:<strong> {{cart.total_cart_price|floatformat:2}} </strong></h5></th>
					</tr>
                    </tfoot>
                    </table>
               <a class="btn btn-warning" id="pay" href="{% url 'cart:render-pdf-invoice' cart.id %}">Pay for Order</a>

		</div>
	</div>
	</div>
            </div>
            </div>
            </div>
         </section>
 </div>
    <script>

    var total  = '{{cart.total_cart_price}}'
    document.getElementById('pay').addEventListener('click', function (e){
        submitForm()
    })
        function submitForm(){
            console.log('payment button cicked')
            var userData ={
                'total':total,
            }

            var url = "/cart/order-porcess/"
            	fetch(url, {
	    		method:'POST',
	    		headers:{
	    			'Content-Type':'applicaiton/json',
	    			'X-CSRFToken':csrftoken,
	    		},
	    		body:JSON.stringify({'form':userData})
	    	})
            .then((response) => response.json())
	    	.then((data) => {
				console.log('Success:', data);
				alert('Payment Done. Thank You {{ request.user.first_name }} for dealing with us.');
				cart = {}
				document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"

				window.location.href = "{% url 'products:products-home' %}"

				})
        }


    </script>

{% endblock content %}

cart/templates/pdf-invoice.html
<head>
        <style>
            * {
                font-size: 15px;


            }
            @page  {
                size: A5;
            }

            table {
                table-layout: fixed;
                width: 100%;
                border: 1px solid black;
            }

            table th {
                text-align: left;
                padding: 3px;
                padding-bottom: 0;
            }

            table td {
                white-space: nowrap;
                overflow: hidden;
                text-overflow: ellipsis;
                padding: 3px;
                padding-bottom: 0;
            }
        </style>
</head>


<body style="size: A5">



            <h3 class="left" style="color: black; text-align: center" >Grocery Store </h3>

            <br/>
            <br/>
            <br/>

           <h3 class="left" style="color: black" > {{ customer.user.first_name }} {{ customer.user.last_name }} </h3>
           <h3 class="left" style="color: black" >Invoice #{{ cart.id }} </h3>
           <h3 class="left" style="color: black" >{{ cart.updated_at.date }} </h3>
                <table class="table-bordered">
                            <thead>
                            <tr>
                                <td>Name</td>
                                <td>Unit Price</td>
                                <td>Quantity</td>
                                <td>Total</td>
                                <td>Currency</td>
                            </tr>
                            </thead>
                            <tbody>
                             {% for item  in cart_items %}
                                <tr>
                                        <td>{{item.product.product_name}}</td>
                                        <td>{{item.product.product_price}} {{item.product.price_currency }}</td>
                                        <td>{{item.quantity}}  {{item.product.unit }} </td>
                                        <td>{{item.get_total|floatformat:2}} </td>
                                        <td>{{item.product.price_currency }}</td>
                                </tr>
                                    {% endfor %}


                            </tbody>
                <tfoot>
                <tr>
                    <th colspan="3" style="text-align: right">Total</th>
                    <th> {{cart.total_cart_price|floatformat:2}} </th>
                    <th>AED  </th>
                </tr>
                </tfoot>

                        </table>
            <hr>
                    <br/>
  <h3 class="left" style="color: black; text-align: center" >Paid - {{ payment_date }} </h3>


</body>